version: "3.9"
services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network
  worker:
    build: .
    command: celery -A app.celery_app.celery_app worker -l info
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - app-network
  db:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      app-network:
        aliases:
          - redis
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
